services:

  database:
    image: mysql:latest
    container_name: MySQL
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DB}
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - '3306:3306'
    restart: always

  app:
    build: .
    container_name: 'token-in-java'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${MYSQL_DB}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DS_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DS_USERNAME}
    ports:
      - '8080:8080'
    depends_on:
      - database
    restart: always
